### ISSUE TITLE
Was mache ich falsch?

### ISSUE THREAD

**Issue by Satch2619** [ProgrammierenM/html-table-layout#1]
Es weerden bei mir keine Farben angezeigt!

hier mein Code:

* {
  box-sizing: border-box;
  font-size: 1rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}

table.content {
  border-collapse: collapse;
  margin: 32px 0;
  min-width: 400px;
  border-radius: 5px 5px 0 0;
  overflow: hidden;
}

table.content thead tr {
  background-color: blue;
  color: white;
  font-weight: bold;
  text-align: left;
}

**Comment by ProgrammierenM** [comment]
Hi, besteht das Problem immer noch? Falls du derjenige bist welcher bei YouTube schon geschrieben hatte, würde ich das Problem hier wieder schließen.
Danke... ;)

**Comment by Satch2619** [comment]
Hallo Mario,

Ja, ich bin derjenige(thailanderleben) der das Problem schon bei Youtube beschrieben hat. Das Problem habe ich gelöst. Danke der Nachfrage!
